import = [
"~/.config/alacritty/themes/zenburn.toml" 
#"~/.config/alacritty/themes/ayu_light.toml"
]

[font]
size = 16

[font.normal]
family = "Inconsolata Nerd Font"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true

[[hints.enabled]]
action = "Copy"
post_processing = false
regex = "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Z"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "I"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "O"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Control|Shift"

[[mouse.bindings]]
action = "IncreaseFontSize"
mods = "Shift"
mouse = "Middle"

[shell]
program = "/bin/zsh"

[window]
dynamic_title = true

[window.padding]
x = 4
y = 0
