color0 #1E2320
color8 #709080

#: black

color1 #D78787
color9 #dca3a3

#: red

color2  #7f9f7f
color10 #c3bf9f

#: green

color3  #dfaf8f
color11 #f0dfaf

#: yellow

color4  #8787d7
color12 #94bff3

#: blue

color5  #dc8cc3
color13 #ec93d3

#: magenta

color6  #8cd0d3
color14 #93e0e3

#: cyan

color7  #dcdccc
color15 #ffffff

#: white

